# Site settings
title: Harmony School of Excellece
subtitle: 
email: youremailaddress@gmail.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/FTCrobotics" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 4401B San Francisco Ave. 
city: Laredo
state: Tx
zip_code: 78041
country: United States of America
phone: (956) 791-0007

# Social settings
500px_url:
facebook_url: https://www.facebook.com/hselaredo/
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/713845/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/HseLaredo

# Sass building
sass:
    sass_dir: _sass

# Build settings
markdown: kramdown
